package com.ohmy.game;

public enum GameState {
    GAME_INIT_BATTLE,
    GAME_TURN_BEGIN,
    PLAYER_TURN_BEGIN,
    PLAYER_TURN_ACTION,
    PLAYER_TURN_END,
    ENEMY_TURN_BEGIN,
    ENEMY_TURN_ACTION,
    ENEMY_TURN_END,
    GAME_RESOLVE_TURN,
    PLAYER_WIN_BATTLE,
    PLAYER_LOSE_BATTLE,
    GAME_PAUSE;
}
